PyCharm Shortcuts.md
Added "Ctrl + Shift + / "command
=> Update PyCharm Shortcuts.md

Mac Keyboard Shortcuts.md
Contributed towards Hacktoberfest
=> Update Mac Keyboard Shortcuts.md

Keyboard Shortcuts for International Characters.md
=> Added the Apostrophe Shortcuts

Keyboard Shortcuts for International Characters.md
=> Updated the CARET Symbols

Excel Keyboard Shortcuts.md
Fixes #6 
I added two excel shorcuts .
=> Added Excel KeyBoard Shortcut

Excel Keyboard Shortcuts.md
Added more cell formatting shortcuts
Added Row and Column Formatting shortcuts
=> Added excel shortcuts

Excel Keyboard Shortcuts.md, Mac Keyboard Shortcuts.md
=> Formated Excel & Mac.

Keyboard Shortcuts for International Characters.md
Added Colon Characters & Formatted Caret and Tilde...
=> Added Colon Characters & Formatted Caret and Tilde

Keyboard Shortcuts for International Characters.md
=> Added Unicode character for hexadecimal

PyCharm Shortcuts.md
Updated the Context Actions in PyCharm!
=> Updated Context Actions in PyCharm

Mac Keyboard Shortcuts.md
* Added "Select code right to the cursor" shortcut in Mac keyboard Shortcuts.MD
=> added a new shortcut

Windows Keyboard Shortcuts.md
windows shortcut added. hacktoberfest pr submit
=> screenshot windows

Windows Keyboard Shortcuts.md, YouTube Keyboard Shortcuts.md
updated shorcuts.md file for windows and youtube
=> shortcuts updated in Windows Key and Youtube

PyCharm Shortcuts.md
Table format to display in more good form.
=> Added Table Format

README.md
by improving the contributors section.
=> Enhanced The Readme.md

README.md
=> Added 2 more contributors

PyCharm Shortcuts.md, README.md
=> Added Navigation Between Code Issues

Android Studio Shortcuts.md, Windows Keyboard Shortcuts.md, YouTube Keyboard Shortcuts.md
Added Shortcut command to split windows screen #9
=> Update Windows Keyboard Shortcuts.md

Microsoft Word Shortcuts.md
Added few Shortcuts for Microsoft Word
Resolves #8
=> Added Shortcuts for Microsoft Word

10 VS Code Shortcuts for Faster Coding.md
Shortcuts are the most helpful tools for developers while coding. Hopefully, it gives you a faster and smarter way to do your work. So, let see the best shortcut keys for the boring stuff that needs to be repeated while coding.
Please merge this and give hacktoberfest accepted label to make it successful pr
=> Created 10 VScode shortcuts for faster coding

Shortcuts in Jupyter Notebook
Added some important shortcuts for Jupyter Notebook
=> Create Shortcuts in Jupyter Notebook

Mac Keyboard Shortcuts.md
Added screenshot of selected area to Mac shortcuts
=> Added to Mac shortcuts

Mac Keyboard Shortcuts.md
added new shortcut. Solution to #1
=> added new shortcut. Solution to #1

IntelliJ Shortcuts.md
=> Update IntelliJ Shortcuts.md

Android Studio Shortcuts.md
I have added a shortcut of "Delete To End of Word". Kindly accept this as my first contribution to open source under Hacktoberfest 2022.
=> Update Android Studio Shortcuts.md

10 VS Code Shortcuts for Faster Coding.md
Added various shortcut keys of VS Code. Issue #73
=> Added VS Code Shortcut keys

YouTube Keyboard Shortcuts.md
#3 
Youtube shortcuts for 360 degree videos
=> youtube shortcuts for 360 degree videos

Android Studio Shortcuts.md
Added "Jump to Declarations" shortcut.
=> Updated Android Studio Shortcuts.md

Atom-Shortcuts.md
Created an md file that contains atom shortcuts for windows and mac users.
=> Atom-Shortcuts

5 Useful VSCode shortcuts to improve your coding speed.md
Added 5 Useful VSCode shortcuts to improve your coding speed.md , please merge this and give hacktoberfest accepted label to make it a successful PR, Thanks
=> Added 5 Useful VSCode shortcuts to improve your coding speed.md

Android Studio Shortcuts.md
**Add Navigation Keys Shortcuts**
I have added single shortcut key for Navigation As per the contribution rule.
=> Add Navigation keys Shortcut 

Github KeyBoard Shortcuts.md
Added Github Keyboard Shortcuts along with Word file that contains various other keyboard shortcuts for the same.
=> Github KeyBoard Shortcuts.md

Google-chrome-keyboard-Shortcuts.md
Added shortcut for home page (Alt+Home) and changed the spelling from sownload to download.
=> Added Shortcut for home page and changed spelling

Windows Keyboard Shortcuts.md
Added a shortcut for opening task manager
=> open-task-manager-shortcut

VsCode_most_useful_shortcut.md
Added Trigger Suggestion and Trigger parameter hints shortcut which are very useful for every developer.
=> Useful-Shortcut-added

Kali-Linux Shortcuts.md
arranged the shortcuts in tablular format.
=> Update Kali-Linux Shortcuts.md  #89

VS Code Shortcuts.md
added global find shortcut in the existing vs code folder.
=> added globalfind shortcut in the existing vsode folder

Ubuntu Keyboard Shortcuts.md
Added Ubuntu Keyboard Shortcuts as well.
=> Ubuntu Keyboard Shortcuts.md

VS Code Shortcuts.md
I have merged [10 VS Code Shortcuts for Faster Coding.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/10%20VS%20Code%20Shortcuts%20for%20Faster%20Coding.md)
[5 Useful VSCode shortcuts to improve your coding speed.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/5%20Useful%20VSCode%20shortcuts%20to%20improve%20your%20coding%20speed.md)
[VsCode_most_useful_shortcut.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/VsCode_most_useful_shortcut.md)  into [VS Code Shortcuts.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/VS%20Code%20Shortcuts.md) folder.
I have merged them in proper format.
=> Merged 3 file into one

Kali-Linux Shortcuts.md
created terminal table and Added Kali Linux terminal command
=> Update Kali-Linux Shortcuts.md

PyCharm Shortcuts.md
=> Added PyCharm Shortcuts

Linux Keyboard Shortcuts.md
closes #78 
**What has been changed?**
- Added some of the popular keyboard shortcuts in the well known linux distros
- Made a tabulated document using markdown(especially using HTML formatting) for these shortcuts
=> Added keyboard shortcuts for some of the popular linux distros like ubuntu,linux mint.

Android Studio Shortcuts.md
I have added a keyboard shortcut for navigating to settings in Android Studio.
=> Added new shortcut for Android Studio

IntelliJ Shortcuts.md
Issue #5
Please verify the PR.
=> Intellij Ctrl space shortcut added

IntelliJ Shortcuts.md
Issue #5 
Please verify the PR.
=> Intellij Ctrl+F shortcut added

IntelliJ Shortcuts.md
Issue #5 
Please verify the PR.
=> Intellij Ctrl+D shortcut added

IntelliJ Shortcuts.md
=> Intellij Ctrl+R shortcut added

Microsoft Word Shortcuts.md
I've added one shortcut ("Open the Styles Pane"), updated the last change I committed. 
Kindly add label for hacktoberfest-accepted if you merge this branch.
Thanks!
=> Update Microsoft Word Shortcuts.md

Google-chrome-keyboard-Shortcuts.md
=> Added new keyboard shortcut to switch tabs

Excel Keyboard Shortcuts.md
Excel Keyboard Shortcuts 
*To select all the contents in a workbook```Ctrl`` + ```A``` 
*To open the create table dialog box```Ctrl + L```
=> Hacktoberfest-2022

Excel Keyboard Shortcuts.md
Updated the excel shortcuts list to add print shortcut and corrected a typo.
=> Updated to add print shortcut
